/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as authAuth_layoutRouteImport } from './routes/(auth)/_auth_layout'
import { Route as unguardedUnguarded_layoutRouteImport } from './routes/(unguarded)/_unguarded_layout'
import { Route as authAuth_layoutAppIndexRouteImport } from './routes/(auth)/_auth_layout/app/index'
import { Route as unguardedUnguarded_layoutActivateAccountIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/activate-account/index'
import { Route as unguardedUnguarded_layoutForgotPasswordIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/forgot-password/index'
import { Route as unguardedUnguarded_layoutInviteIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/invite/index'
import { Route as unguardedUnguarded_layoutLoginIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/login/index'
import { Route as unguardedUnguarded_layoutNewVerifyIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/new-verify/index'
import { Route as unguardedUnguarded_layoutRegisterIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/register/index'
import { Route as unguardedUnguarded_layoutResetPasswordIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/reset-password/index'
import { Route as unguardedUnguarded_layoutVerificationResultRouteImport } from './routes/(unguarded)/_unguarded_layout/verification/result'
import { Route as unguardedUnguarded_layoutVerifyResultRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/result'
import { Route as authAuth_layoutAppApikeysIndexRouteImport } from './routes/(auth)/_auth_layout/app/apikeys/index'
import { Route as authAuth_layoutAppBillingIndexRouteImport } from './routes/(auth)/_auth_layout/app/billing/index'
import { Route as authAuth_layoutAppKycIndexRouteImport } from './routes/(auth)/_auth_layout/app/kyc/index'
import { Route as authAuth_layoutAppProductsIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/index'
import { Route as authAuth_layoutAppProfileIndexRouteImport } from './routes/(auth)/_auth_layout/app/profile/index'
import { Route as authAuth_layoutAppReportsIndexRouteImport } from './routes/(auth)/_auth_layout/app/reports/index'
import { Route as authAuth_layoutAppTeamIndexRouteImport } from './routes/(auth)/_auth_layout/app/team/index'
import { Route as authAuth_layoutAppWebhooksIndexRouteImport } from './routes/(auth)/_auth_layout/app/webhooks/index'
import { Route as unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/new-verify/$token/index'
import { Route as unguardedUnguarded_layoutVerifyLinkIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/$link/index'
import { Route as authAuth_layoutAppProductsAddressVerificationIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/address-verification/index'
import { Route as authAuth_layoutAppProductsAmlScreeningIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/aml-screening/index'
import { Route as authAuth_layoutAppProductsBusinessAmlScreeningIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/business-aml-screening/index'
import { Route as authAuth_layoutAppProductsCryptoWalletScreeningIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/crypto-wallet-screening/index'
import { Route as authAuth_layoutAppProductsDocumentVerificationIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/document-verification/index'
import { Route as authAuth_layoutAppProductsFacialScreeningIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/facial-screening/index'
import { Route as authAuth_layoutAppProductsGovernmentRegistryChecksIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/government-registry-checks/index'
import { Route as authAuth_layoutAppProductsKybIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/kyb/index'
import { Route as authAuth_layoutAppProductsMixedVerificationsIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/mixed-verifications/index'
import { Route as authAuth_layoutAppProductsRiskAssessmentIndexRouteImport } from './routes/(auth)/_auth_layout/app/products/risk-assessment/index'
import { Route as authAuth_layoutAppReportsIdIndexRouteImport } from './routes/(auth)/_auth_layout/app/reports/$id/index'
import { Route as authAuth_layoutAppTeamActiveUsersIndexRouteImport } from './routes/(auth)/_auth_layout/app/team/active-users/index'
import { Route as authAuth_layoutAppTeamInvitationsIndexRouteImport } from './routes/(auth)/_auth_layout/app/team/invitations/index'
import { Route as authAuth_layoutAppReportsBatchBatchIdIndexRouteImport } from './routes/(auth)/_auth_layout/app/reports/batch/$batchId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuth_layoutRoute = authAuth_layoutRouteImport.update({
  id: '/(auth)/_auth_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutRoute =
  unguardedUnguarded_layoutRouteImport.update({
    id: '/(unguarded)/_unguarded_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuth_layoutAppIndexRoute = authAuth_layoutAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => authAuth_layoutRoute,
} as any)
const unguardedUnguarded_layoutActivateAccountIndexRoute =
  unguardedUnguarded_layoutActivateAccountIndexRouteImport.update({
    id: '/activate-account/',
    path: '/activate-account/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutForgotPasswordIndexRoute =
  unguardedUnguarded_layoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutInviteIndexRoute =
  unguardedUnguarded_layoutInviteIndexRouteImport.update({
    id: '/invite/',
    path: '/invite/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutLoginIndexRoute =
  unguardedUnguarded_layoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutNewVerifyIndexRoute =
  unguardedUnguarded_layoutNewVerifyIndexRouteImport.update({
    id: '/new-verify/',
    path: '/new-verify/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutRegisterIndexRoute =
  unguardedUnguarded_layoutRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutResetPasswordIndexRoute =
  unguardedUnguarded_layoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerificationResultRoute =
  unguardedUnguarded_layoutVerificationResultRouteImport.update({
    id: '/verification/result',
    path: '/verification/result',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyResultRoute =
  unguardedUnguarded_layoutVerifyResultRouteImport.update({
    id: '/verify/result',
    path: '/verify/result',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const authAuth_layoutAppApikeysIndexRoute =
  authAuth_layoutAppApikeysIndexRouteImport.update({
    id: '/app/apikeys/',
    path: '/app/apikeys/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppBillingIndexRoute =
  authAuth_layoutAppBillingIndexRouteImport.update({
    id: '/app/billing/',
    path: '/app/billing/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppKycIndexRoute =
  authAuth_layoutAppKycIndexRouteImport.update({
    id: '/app/kyc/',
    path: '/app/kyc/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsIndexRoute =
  authAuth_layoutAppProductsIndexRouteImport.update({
    id: '/app/products/',
    path: '/app/products/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProfileIndexRoute =
  authAuth_layoutAppProfileIndexRouteImport.update({
    id: '/app/profile/',
    path: '/app/profile/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppReportsIndexRoute =
  authAuth_layoutAppReportsIndexRouteImport.update({
    id: '/app/reports/',
    path: '/app/reports/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTeamIndexRoute =
  authAuth_layoutAppTeamIndexRouteImport.update({
    id: '/app/team/',
    path: '/app/team/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppWebhooksIndexRoute =
  authAuth_layoutAppWebhooksIndexRouteImport.update({
    id: '/app/webhooks/',
    path: '/app/webhooks/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const unguardedUnguarded_layoutNewVerifyTokenIndexRoute =
  unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport.update({
    id: '/new-verify/$token/',
    path: '/new-verify/$token/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyLinkIndexRoute =
  unguardedUnguarded_layoutVerifyLinkIndexRouteImport.update({
    id: '/verify/$link/',
    path: '/verify/$link/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const authAuth_layoutAppProductsAddressVerificationIndexRoute =
  authAuth_layoutAppProductsAddressVerificationIndexRouteImport.update({
    id: '/app/products/address-verification/',
    path: '/app/products/address-verification/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsAmlScreeningIndexRoute =
  authAuth_layoutAppProductsAmlScreeningIndexRouteImport.update({
    id: '/app/products/aml-screening/',
    path: '/app/products/aml-screening/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute =
  authAuth_layoutAppProductsBusinessAmlScreeningIndexRouteImport.update({
    id: '/app/products/business-aml-screening/',
    path: '/app/products/business-aml-screening/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute =
  authAuth_layoutAppProductsCryptoWalletScreeningIndexRouteImport.update({
    id: '/app/products/crypto-wallet-screening/',
    path: '/app/products/crypto-wallet-screening/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsDocumentVerificationIndexRoute =
  authAuth_layoutAppProductsDocumentVerificationIndexRouteImport.update({
    id: '/app/products/document-verification/',
    path: '/app/products/document-verification/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsFacialScreeningIndexRoute =
  authAuth_layoutAppProductsFacialScreeningIndexRouteImport.update({
    id: '/app/products/facial-screening/',
    path: '/app/products/facial-screening/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute =
  authAuth_layoutAppProductsGovernmentRegistryChecksIndexRouteImport.update({
    id: '/app/products/government-registry-checks/',
    path: '/app/products/government-registry-checks/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsKybIndexRoute =
  authAuth_layoutAppProductsKybIndexRouteImport.update({
    id: '/app/products/kyb/',
    path: '/app/products/kyb/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsMixedVerificationsIndexRoute =
  authAuth_layoutAppProductsMixedVerificationsIndexRouteImport.update({
    id: '/app/products/mixed-verifications/',
    path: '/app/products/mixed-verifications/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppProductsRiskAssessmentIndexRoute =
  authAuth_layoutAppProductsRiskAssessmentIndexRouteImport.update({
    id: '/app/products/risk-assessment/',
    path: '/app/products/risk-assessment/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppReportsIdIndexRoute =
  authAuth_layoutAppReportsIdIndexRouteImport.update({
    id: '/app/reports/$id/',
    path: '/app/reports/$id/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTeamActiveUsersIndexRoute =
  authAuth_layoutAppTeamActiveUsersIndexRouteImport.update({
    id: '/app/team/active-users/',
    path: '/app/team/active-users/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppTeamInvitationsIndexRoute =
  authAuth_layoutAppTeamInvitationsIndexRouteImport.update({
    id: '/app/team/invitations/',
    path: '/app/team/invitations/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)
const authAuth_layoutAppReportsBatchBatchIdIndexRoute =
  authAuth_layoutAppReportsBatchBatchIdIndexRouteImport.update({
    id: '/app/reports/batch/$batchId/',
    path: '/app/reports/batch/$batchId/',
    getParentRoute: () => authAuth_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/app/': typeof authAuth_layoutAppIndexRoute
  '/activate-account/': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/forgot-password/': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/invite/': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/new-verify/': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/register/': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/reset-password/': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/app/apikeys/': typeof authAuth_layoutAppApikeysIndexRoute
  '/app/billing/': typeof authAuth_layoutAppBillingIndexRoute
  '/app/kyc/': typeof authAuth_layoutAppKycIndexRoute
  '/app/products/': typeof authAuth_layoutAppProductsIndexRoute
  '/app/profile/': typeof authAuth_layoutAppProfileIndexRoute
  '/app/reports/': typeof authAuth_layoutAppReportsIndexRoute
  '/app/team/': typeof authAuth_layoutAppTeamIndexRoute
  '/app/webhooks/': typeof authAuth_layoutAppWebhooksIndexRoute
  '/new-verify/$token/': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
  '/app/products/address-verification/': typeof authAuth_layoutAppProductsAddressVerificationIndexRoute
  '/app/products/aml-screening/': typeof authAuth_layoutAppProductsAmlScreeningIndexRoute
  '/app/products/business-aml-screening/': typeof authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute
  '/app/products/crypto-wallet-screening/': typeof authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute
  '/app/products/document-verification/': typeof authAuth_layoutAppProductsDocumentVerificationIndexRoute
  '/app/products/facial-screening/': typeof authAuth_layoutAppProductsFacialScreeningIndexRoute
  '/app/products/government-registry-checks/': typeof authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute
  '/app/products/kyb/': typeof authAuth_layoutAppProductsKybIndexRoute
  '/app/products/mixed-verifications/': typeof authAuth_layoutAppProductsMixedVerificationsIndexRoute
  '/app/products/risk-assessment/': typeof authAuth_layoutAppProductsRiskAssessmentIndexRoute
  '/app/reports/$id/': typeof authAuth_layoutAppReportsIdIndexRoute
  '/app/team/active-users/': typeof authAuth_layoutAppTeamActiveUsersIndexRoute
  '/app/team/invitations/': typeof authAuth_layoutAppTeamInvitationsIndexRoute
  '/app/reports/batch/$batchId/': typeof authAuth_layoutAppReportsBatchBatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/app': typeof authAuth_layoutAppIndexRoute
  '/activate-account': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/forgot-password': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/invite': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/login': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/new-verify': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/register': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/reset-password': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/app/apikeys': typeof authAuth_layoutAppApikeysIndexRoute
  '/app/billing': typeof authAuth_layoutAppBillingIndexRoute
  '/app/kyc': typeof authAuth_layoutAppKycIndexRoute
  '/app/products': typeof authAuth_layoutAppProductsIndexRoute
  '/app/profile': typeof authAuth_layoutAppProfileIndexRoute
  '/app/reports': typeof authAuth_layoutAppReportsIndexRoute
  '/app/team': typeof authAuth_layoutAppTeamIndexRoute
  '/app/webhooks': typeof authAuth_layoutAppWebhooksIndexRoute
  '/new-verify/$token': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/verify/$link': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
  '/app/products/address-verification': typeof authAuth_layoutAppProductsAddressVerificationIndexRoute
  '/app/products/aml-screening': typeof authAuth_layoutAppProductsAmlScreeningIndexRoute
  '/app/products/business-aml-screening': typeof authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute
  '/app/products/crypto-wallet-screening': typeof authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute
  '/app/products/document-verification': typeof authAuth_layoutAppProductsDocumentVerificationIndexRoute
  '/app/products/facial-screening': typeof authAuth_layoutAppProductsFacialScreeningIndexRoute
  '/app/products/government-registry-checks': typeof authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute
  '/app/products/kyb': typeof authAuth_layoutAppProductsKybIndexRoute
  '/app/products/mixed-verifications': typeof authAuth_layoutAppProductsMixedVerificationsIndexRoute
  '/app/products/risk-assessment': typeof authAuth_layoutAppProductsRiskAssessmentIndexRoute
  '/app/reports/$id': typeof authAuth_layoutAppReportsIdIndexRoute
  '/app/team/active-users': typeof authAuth_layoutAppTeamActiveUsersIndexRoute
  '/app/team/invitations': typeof authAuth_layoutAppTeamInvitationsIndexRoute
  '/app/reports/batch/$batchId': typeof authAuth_layoutAppReportsBatchBatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/(auth)/_auth_layout': typeof authAuth_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout': typeof unguardedUnguarded_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/(unguarded)/_unguarded_layout/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/(auth)/_auth_layout/app/': typeof authAuth_layoutAppIndexRoute
  '/(unguarded)/_unguarded_layout/activate-account/': typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  '/(unguarded)/_unguarded_layout/forgot-password/': typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  '/(unguarded)/_unguarded_layout/invite/': typeof unguardedUnguarded_layoutInviteIndexRoute
  '/(unguarded)/_unguarded_layout/login/': typeof unguardedUnguarded_layoutLoginIndexRoute
  '/(unguarded)/_unguarded_layout/new-verify/': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/(unguarded)/_unguarded_layout/register/': typeof unguardedUnguarded_layoutRegisterIndexRoute
  '/(unguarded)/_unguarded_layout/reset-password/': typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  '/(auth)/_auth_layout/app/apikeys/': typeof authAuth_layoutAppApikeysIndexRoute
  '/(auth)/_auth_layout/app/billing/': typeof authAuth_layoutAppBillingIndexRoute
  '/(auth)/_auth_layout/app/kyc/': typeof authAuth_layoutAppKycIndexRoute
  '/(auth)/_auth_layout/app/products/': typeof authAuth_layoutAppProductsIndexRoute
  '/(auth)/_auth_layout/app/profile/': typeof authAuth_layoutAppProfileIndexRoute
  '/(auth)/_auth_layout/app/reports/': typeof authAuth_layoutAppReportsIndexRoute
  '/(auth)/_auth_layout/app/team/': typeof authAuth_layoutAppTeamIndexRoute
  '/(auth)/_auth_layout/app/webhooks/': typeof authAuth_layoutAppWebhooksIndexRoute
  '/(unguarded)/_unguarded_layout/new-verify/$token/': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/(unguarded)/_unguarded_layout/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
  '/(auth)/_auth_layout/app/products/address-verification/': typeof authAuth_layoutAppProductsAddressVerificationIndexRoute
  '/(auth)/_auth_layout/app/products/aml-screening/': typeof authAuth_layoutAppProductsAmlScreeningIndexRoute
  '/(auth)/_auth_layout/app/products/business-aml-screening/': typeof authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute
  '/(auth)/_auth_layout/app/products/crypto-wallet-screening/': typeof authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute
  '/(auth)/_auth_layout/app/products/document-verification/': typeof authAuth_layoutAppProductsDocumentVerificationIndexRoute
  '/(auth)/_auth_layout/app/products/facial-screening/': typeof authAuth_layoutAppProductsFacialScreeningIndexRoute
  '/(auth)/_auth_layout/app/products/government-registry-checks/': typeof authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute
  '/(auth)/_auth_layout/app/products/kyb/': typeof authAuth_layoutAppProductsKybIndexRoute
  '/(auth)/_auth_layout/app/products/mixed-verifications/': typeof authAuth_layoutAppProductsMixedVerificationsIndexRoute
  '/(auth)/_auth_layout/app/products/risk-assessment/': typeof authAuth_layoutAppProductsRiskAssessmentIndexRoute
  '/(auth)/_auth_layout/app/reports/$id/': typeof authAuth_layoutAppReportsIdIndexRoute
  '/(auth)/_auth_layout/app/team/active-users/': typeof authAuth_layoutAppTeamActiveUsersIndexRoute
  '/(auth)/_auth_layout/app/team/invitations/': typeof authAuth_layoutAppTeamInvitationsIndexRoute
  '/(auth)/_auth_layout/app/reports/batch/$batchId/': typeof authAuth_layoutAppReportsBatchBatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/verification/result'
    | '/verify/result'
    | '/app/'
    | '/activate-account/'
    | '/forgot-password/'
    | '/invite/'
    | '/login/'
    | '/new-verify/'
    | '/register/'
    | '/reset-password/'
    | '/app/apikeys/'
    | '/app/billing/'
    | '/app/kyc/'
    | '/app/products/'
    | '/app/profile/'
    | '/app/reports/'
    | '/app/team/'
    | '/app/webhooks/'
    | '/new-verify/$token/'
    | '/verify/$link/'
    | '/app/products/address-verification/'
    | '/app/products/aml-screening/'
    | '/app/products/business-aml-screening/'
    | '/app/products/crypto-wallet-screening/'
    | '/app/products/document-verification/'
    | '/app/products/facial-screening/'
    | '/app/products/government-registry-checks/'
    | '/app/products/kyb/'
    | '/app/products/mixed-verifications/'
    | '/app/products/risk-assessment/'
    | '/app/reports/$id/'
    | '/app/team/active-users/'
    | '/app/team/invitations/'
    | '/app/reports/batch/$batchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/verification/result'
    | '/verify/result'
    | '/app'
    | '/activate-account'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/new-verify'
    | '/register'
    | '/reset-password'
    | '/app/apikeys'
    | '/app/billing'
    | '/app/kyc'
    | '/app/products'
    | '/app/profile'
    | '/app/reports'
    | '/app/team'
    | '/app/webhooks'
    | '/new-verify/$token'
    | '/verify/$link'
    | '/app/products/address-verification'
    | '/app/products/aml-screening'
    | '/app/products/business-aml-screening'
    | '/app/products/crypto-wallet-screening'
    | '/app/products/document-verification'
    | '/app/products/facial-screening'
    | '/app/products/government-registry-checks'
    | '/app/products/kyb'
    | '/app/products/mixed-verifications'
    | '/app/products/risk-assessment'
    | '/app/reports/$id'
    | '/app/team/active-users'
    | '/app/team/invitations'
    | '/app/reports/batch/$batchId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/(auth)/_auth_layout'
    | '/(unguarded)/_unguarded_layout'
    | '/(unguarded)/_unguarded_layout/verification/result'
    | '/(unguarded)/_unguarded_layout/verify/result'
    | '/(auth)/_auth_layout/app/'
    | '/(unguarded)/_unguarded_layout/activate-account/'
    | '/(unguarded)/_unguarded_layout/forgot-password/'
    | '/(unguarded)/_unguarded_layout/invite/'
    | '/(unguarded)/_unguarded_layout/login/'
    | '/(unguarded)/_unguarded_layout/new-verify/'
    | '/(unguarded)/_unguarded_layout/register/'
    | '/(unguarded)/_unguarded_layout/reset-password/'
    | '/(auth)/_auth_layout/app/apikeys/'
    | '/(auth)/_auth_layout/app/billing/'
    | '/(auth)/_auth_layout/app/kyc/'
    | '/(auth)/_auth_layout/app/products/'
    | '/(auth)/_auth_layout/app/profile/'
    | '/(auth)/_auth_layout/app/reports/'
    | '/(auth)/_auth_layout/app/team/'
    | '/(auth)/_auth_layout/app/webhooks/'
    | '/(unguarded)/_unguarded_layout/new-verify/$token/'
    | '/(unguarded)/_unguarded_layout/verify/$link/'
    | '/(auth)/_auth_layout/app/products/address-verification/'
    | '/(auth)/_auth_layout/app/products/aml-screening/'
    | '/(auth)/_auth_layout/app/products/business-aml-screening/'
    | '/(auth)/_auth_layout/app/products/crypto-wallet-screening/'
    | '/(auth)/_auth_layout/app/products/document-verification/'
    | '/(auth)/_auth_layout/app/products/facial-screening/'
    | '/(auth)/_auth_layout/app/products/government-registry-checks/'
    | '/(auth)/_auth_layout/app/products/kyb/'
    | '/(auth)/_auth_layout/app/products/mixed-verifications/'
    | '/(auth)/_auth_layout/app/products/risk-assessment/'
    | '/(auth)/_auth_layout/app/reports/$id/'
    | '/(auth)/_auth_layout/app/team/active-users/'
    | '/(auth)/_auth_layout/app/team/invitations/'
    | '/(auth)/_auth_layout/app/reports/batch/$batchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  authAuth_layoutRoute: typeof authAuth_layoutRouteWithChildren
  unguardedUnguarded_layoutRoute: typeof unguardedUnguarded_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth_layout': {
      id: '/(auth)/_auth_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuth_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout': {
      id: '/(unguarded)/_unguarded_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unguardedUnguarded_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth_layout/app/': {
      id: '/(auth)/_auth_layout/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof authAuth_layoutAppIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/activate-account/': {
      id: '/(unguarded)/_unguarded_layout/activate-account/'
      path: '/activate-account'
      fullPath: '/activate-account/'
      preLoaderRoute: typeof unguardedUnguarded_layoutActivateAccountIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/forgot-password/': {
      id: '/(unguarded)/_unguarded_layout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof unguardedUnguarded_layoutForgotPasswordIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/invite/': {
      id: '/(unguarded)/_unguarded_layout/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof unguardedUnguarded_layoutInviteIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/login/': {
      id: '/(unguarded)/_unguarded_layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof unguardedUnguarded_layoutLoginIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/new-verify/': {
      id: '/(unguarded)/_unguarded_layout/new-verify/'
      path: '/new-verify'
      fullPath: '/new-verify/'
      preLoaderRoute: typeof unguardedUnguarded_layoutNewVerifyIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/register/': {
      id: '/(unguarded)/_unguarded_layout/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof unguardedUnguarded_layoutRegisterIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/reset-password/': {
      id: '/(unguarded)/_unguarded_layout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof unguardedUnguarded_layoutResetPasswordIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verification/result': {
      id: '/(unguarded)/_unguarded_layout/verification/result'
      path: '/verification/result'
      fullPath: '/verification/result'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerificationResultRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/result': {
      id: '/(unguarded)/_unguarded_layout/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyResultRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(auth)/_auth_layout/app/apikeys/': {
      id: '/(auth)/_auth_layout/app/apikeys/'
      path: '/app/apikeys'
      fullPath: '/app/apikeys/'
      preLoaderRoute: typeof authAuth_layoutAppApikeysIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/billing/': {
      id: '/(auth)/_auth_layout/app/billing/'
      path: '/app/billing'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof authAuth_layoutAppBillingIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/kyc/': {
      id: '/(auth)/_auth_layout/app/kyc/'
      path: '/app/kyc'
      fullPath: '/app/kyc/'
      preLoaderRoute: typeof authAuth_layoutAppKycIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/': {
      id: '/(auth)/_auth_layout/app/products/'
      path: '/app/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof authAuth_layoutAppProductsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/profile/': {
      id: '/(auth)/_auth_layout/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof authAuth_layoutAppProfileIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/reports/': {
      id: '/(auth)/_auth_layout/app/reports/'
      path: '/app/reports'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof authAuth_layoutAppReportsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/team/': {
      id: '/(auth)/_auth_layout/app/team/'
      path: '/app/team'
      fullPath: '/app/team/'
      preLoaderRoute: typeof authAuth_layoutAppTeamIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/webhooks/': {
      id: '/(auth)/_auth_layout/app/webhooks/'
      path: '/app/webhooks'
      fullPath: '/app/webhooks/'
      preLoaderRoute: typeof authAuth_layoutAppWebhooksIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/new-verify/$token/': {
      id: '/(unguarded)/_unguarded_layout/new-verify/$token/'
      path: '/new-verify/$token'
      fullPath: '/new-verify/$token/'
      preLoaderRoute: typeof unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/$link/': {
      id: '/(unguarded)/_unguarded_layout/verify/$link/'
      path: '/verify/$link'
      fullPath: '/verify/$link/'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/address-verification/': {
      id: '/(auth)/_auth_layout/app/products/address-verification/'
      path: '/app/products/address-verification'
      fullPath: '/app/products/address-verification/'
      preLoaderRoute: typeof authAuth_layoutAppProductsAddressVerificationIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/aml-screening/': {
      id: '/(auth)/_auth_layout/app/products/aml-screening/'
      path: '/app/products/aml-screening'
      fullPath: '/app/products/aml-screening/'
      preLoaderRoute: typeof authAuth_layoutAppProductsAmlScreeningIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/business-aml-screening/': {
      id: '/(auth)/_auth_layout/app/products/business-aml-screening/'
      path: '/app/products/business-aml-screening'
      fullPath: '/app/products/business-aml-screening/'
      preLoaderRoute: typeof authAuth_layoutAppProductsBusinessAmlScreeningIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/crypto-wallet-screening/': {
      id: '/(auth)/_auth_layout/app/products/crypto-wallet-screening/'
      path: '/app/products/crypto-wallet-screening'
      fullPath: '/app/products/crypto-wallet-screening/'
      preLoaderRoute: typeof authAuth_layoutAppProductsCryptoWalletScreeningIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/document-verification/': {
      id: '/(auth)/_auth_layout/app/products/document-verification/'
      path: '/app/products/document-verification'
      fullPath: '/app/products/document-verification/'
      preLoaderRoute: typeof authAuth_layoutAppProductsDocumentVerificationIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/facial-screening/': {
      id: '/(auth)/_auth_layout/app/products/facial-screening/'
      path: '/app/products/facial-screening'
      fullPath: '/app/products/facial-screening/'
      preLoaderRoute: typeof authAuth_layoutAppProductsFacialScreeningIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/government-registry-checks/': {
      id: '/(auth)/_auth_layout/app/products/government-registry-checks/'
      path: '/app/products/government-registry-checks'
      fullPath: '/app/products/government-registry-checks/'
      preLoaderRoute: typeof authAuth_layoutAppProductsGovernmentRegistryChecksIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/kyb/': {
      id: '/(auth)/_auth_layout/app/products/kyb/'
      path: '/app/products/kyb'
      fullPath: '/app/products/kyb/'
      preLoaderRoute: typeof authAuth_layoutAppProductsKybIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/mixed-verifications/': {
      id: '/(auth)/_auth_layout/app/products/mixed-verifications/'
      path: '/app/products/mixed-verifications'
      fullPath: '/app/products/mixed-verifications/'
      preLoaderRoute: typeof authAuth_layoutAppProductsMixedVerificationsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/products/risk-assessment/': {
      id: '/(auth)/_auth_layout/app/products/risk-assessment/'
      path: '/app/products/risk-assessment'
      fullPath: '/app/products/risk-assessment/'
      preLoaderRoute: typeof authAuth_layoutAppProductsRiskAssessmentIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/reports/$id/': {
      id: '/(auth)/_auth_layout/app/reports/$id/'
      path: '/app/reports/$id'
      fullPath: '/app/reports/$id/'
      preLoaderRoute: typeof authAuth_layoutAppReportsIdIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/team/active-users/': {
      id: '/(auth)/_auth_layout/app/team/active-users/'
      path: '/app/team/active-users'
      fullPath: '/app/team/active-users/'
      preLoaderRoute: typeof authAuth_layoutAppTeamActiveUsersIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/team/invitations/': {
      id: '/(auth)/_auth_layout/app/team/invitations/'
      path: '/app/team/invitations'
      fullPath: '/app/team/invitations/'
      preLoaderRoute: typeof authAuth_layoutAppTeamInvitationsIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
    '/(auth)/_auth_layout/app/reports/batch/$batchId/': {
      id: '/(auth)/_auth_layout/app/reports/batch/$batchId/'
      path: '/app/reports/batch/$batchId'
      fullPath: '/app/reports/batch/$batchId/'
      preLoaderRoute: typeof authAuth_layoutAppReportsBatchBatchIdIndexRouteImport
      parentRoute: typeof authAuth_layoutRoute
    }
  }
}

interface authAuth_layoutRouteChildren {
  authAuth_layoutAppIndexRoute: typeof authAuth_layoutAppIndexRoute
  authAuth_layoutAppApikeysIndexRoute: typeof authAuth_layoutAppApikeysIndexRoute
  authAuth_layoutAppBillingIndexRoute: typeof authAuth_layoutAppBillingIndexRoute
  authAuth_layoutAppKycIndexRoute: typeof authAuth_layoutAppKycIndexRoute
  authAuth_layoutAppProductsIndexRoute: typeof authAuth_layoutAppProductsIndexRoute
  authAuth_layoutAppProfileIndexRoute: typeof authAuth_layoutAppProfileIndexRoute
  authAuth_layoutAppReportsIndexRoute: typeof authAuth_layoutAppReportsIndexRoute
  authAuth_layoutAppTeamIndexRoute: typeof authAuth_layoutAppTeamIndexRoute
  authAuth_layoutAppWebhooksIndexRoute: typeof authAuth_layoutAppWebhooksIndexRoute
  authAuth_layoutAppProductsAddressVerificationIndexRoute: typeof authAuth_layoutAppProductsAddressVerificationIndexRoute
  authAuth_layoutAppProductsAmlScreeningIndexRoute: typeof authAuth_layoutAppProductsAmlScreeningIndexRoute
  authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute: typeof authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute
  authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute: typeof authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute
  authAuth_layoutAppProductsDocumentVerificationIndexRoute: typeof authAuth_layoutAppProductsDocumentVerificationIndexRoute
  authAuth_layoutAppProductsFacialScreeningIndexRoute: typeof authAuth_layoutAppProductsFacialScreeningIndexRoute
  authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute: typeof authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute
  authAuth_layoutAppProductsKybIndexRoute: typeof authAuth_layoutAppProductsKybIndexRoute
  authAuth_layoutAppProductsMixedVerificationsIndexRoute: typeof authAuth_layoutAppProductsMixedVerificationsIndexRoute
  authAuth_layoutAppProductsRiskAssessmentIndexRoute: typeof authAuth_layoutAppProductsRiskAssessmentIndexRoute
  authAuth_layoutAppReportsIdIndexRoute: typeof authAuth_layoutAppReportsIdIndexRoute
  authAuth_layoutAppTeamActiveUsersIndexRoute: typeof authAuth_layoutAppTeamActiveUsersIndexRoute
  authAuth_layoutAppTeamInvitationsIndexRoute: typeof authAuth_layoutAppTeamInvitationsIndexRoute
  authAuth_layoutAppReportsBatchBatchIdIndexRoute: typeof authAuth_layoutAppReportsBatchBatchIdIndexRoute
}

const authAuth_layoutRouteChildren: authAuth_layoutRouteChildren = {
  authAuth_layoutAppIndexRoute: authAuth_layoutAppIndexRoute,
  authAuth_layoutAppApikeysIndexRoute: authAuth_layoutAppApikeysIndexRoute,
  authAuth_layoutAppBillingIndexRoute: authAuth_layoutAppBillingIndexRoute,
  authAuth_layoutAppKycIndexRoute: authAuth_layoutAppKycIndexRoute,
  authAuth_layoutAppProductsIndexRoute: authAuth_layoutAppProductsIndexRoute,
  authAuth_layoutAppProfileIndexRoute: authAuth_layoutAppProfileIndexRoute,
  authAuth_layoutAppReportsIndexRoute: authAuth_layoutAppReportsIndexRoute,
  authAuth_layoutAppTeamIndexRoute: authAuth_layoutAppTeamIndexRoute,
  authAuth_layoutAppWebhooksIndexRoute: authAuth_layoutAppWebhooksIndexRoute,
  authAuth_layoutAppProductsAddressVerificationIndexRoute:
    authAuth_layoutAppProductsAddressVerificationIndexRoute,
  authAuth_layoutAppProductsAmlScreeningIndexRoute:
    authAuth_layoutAppProductsAmlScreeningIndexRoute,
  authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute:
    authAuth_layoutAppProductsBusinessAmlScreeningIndexRoute,
  authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute:
    authAuth_layoutAppProductsCryptoWalletScreeningIndexRoute,
  authAuth_layoutAppProductsDocumentVerificationIndexRoute:
    authAuth_layoutAppProductsDocumentVerificationIndexRoute,
  authAuth_layoutAppProductsFacialScreeningIndexRoute:
    authAuth_layoutAppProductsFacialScreeningIndexRoute,
  authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute:
    authAuth_layoutAppProductsGovernmentRegistryChecksIndexRoute,
  authAuth_layoutAppProductsKybIndexRoute:
    authAuth_layoutAppProductsKybIndexRoute,
  authAuth_layoutAppProductsMixedVerificationsIndexRoute:
    authAuth_layoutAppProductsMixedVerificationsIndexRoute,
  authAuth_layoutAppProductsRiskAssessmentIndexRoute:
    authAuth_layoutAppProductsRiskAssessmentIndexRoute,
  authAuth_layoutAppReportsIdIndexRoute: authAuth_layoutAppReportsIdIndexRoute,
  authAuth_layoutAppTeamActiveUsersIndexRoute:
    authAuth_layoutAppTeamActiveUsersIndexRoute,
  authAuth_layoutAppTeamInvitationsIndexRoute:
    authAuth_layoutAppTeamInvitationsIndexRoute,
  authAuth_layoutAppReportsBatchBatchIdIndexRoute:
    authAuth_layoutAppReportsBatchBatchIdIndexRoute,
}

const authAuth_layoutRouteWithChildren = authAuth_layoutRoute._addFileChildren(
  authAuth_layoutRouteChildren,
)

interface unguardedUnguarded_layoutRouteChildren {
  unguardedUnguarded_layoutVerificationResultRoute: typeof unguardedUnguarded_layoutVerificationResultRoute
  unguardedUnguarded_layoutVerifyResultRoute: typeof unguardedUnguarded_layoutVerifyResultRoute
  unguardedUnguarded_layoutActivateAccountIndexRoute: typeof unguardedUnguarded_layoutActivateAccountIndexRoute
  unguardedUnguarded_layoutForgotPasswordIndexRoute: typeof unguardedUnguarded_layoutForgotPasswordIndexRoute
  unguardedUnguarded_layoutInviteIndexRoute: typeof unguardedUnguarded_layoutInviteIndexRoute
  unguardedUnguarded_layoutLoginIndexRoute: typeof unguardedUnguarded_layoutLoginIndexRoute
  unguardedUnguarded_layoutNewVerifyIndexRoute: typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  unguardedUnguarded_layoutRegisterIndexRoute: typeof unguardedUnguarded_layoutRegisterIndexRoute
  unguardedUnguarded_layoutResetPasswordIndexRoute: typeof unguardedUnguarded_layoutResetPasswordIndexRoute
  unguardedUnguarded_layoutNewVerifyTokenIndexRoute: typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  unguardedUnguarded_layoutVerifyLinkIndexRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}

const unguardedUnguarded_layoutRouteChildren: unguardedUnguarded_layoutRouteChildren =
  {
    unguardedUnguarded_layoutVerificationResultRoute:
      unguardedUnguarded_layoutVerificationResultRoute,
    unguardedUnguarded_layoutVerifyResultRoute:
      unguardedUnguarded_layoutVerifyResultRoute,
    unguardedUnguarded_layoutActivateAccountIndexRoute:
      unguardedUnguarded_layoutActivateAccountIndexRoute,
    unguardedUnguarded_layoutForgotPasswordIndexRoute:
      unguardedUnguarded_layoutForgotPasswordIndexRoute,
    unguardedUnguarded_layoutInviteIndexRoute:
      unguardedUnguarded_layoutInviteIndexRoute,
    unguardedUnguarded_layoutLoginIndexRoute:
      unguardedUnguarded_layoutLoginIndexRoute,
    unguardedUnguarded_layoutNewVerifyIndexRoute:
      unguardedUnguarded_layoutNewVerifyIndexRoute,
    unguardedUnguarded_layoutRegisterIndexRoute:
      unguardedUnguarded_layoutRegisterIndexRoute,
    unguardedUnguarded_layoutResetPasswordIndexRoute:
      unguardedUnguarded_layoutResetPasswordIndexRoute,
    unguardedUnguarded_layoutNewVerifyTokenIndexRoute:
      unguardedUnguarded_layoutNewVerifyTokenIndexRoute,
    unguardedUnguarded_layoutVerifyLinkIndexRoute:
      unguardedUnguarded_layoutVerifyLinkIndexRoute,
  }

const unguardedUnguarded_layoutRouteWithChildren =
  unguardedUnguarded_layoutRoute._addFileChildren(
    unguardedUnguarded_layoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  authAuth_layoutRoute: authAuth_layoutRouteWithChildren,
  unguardedUnguarded_layoutRoute: unguardedUnguarded_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
