/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as unguardedUnguarded_layoutRouteImport } from './routes/(unguarded)/_unguarded_layout'
import { Route as unguardedUnguarded_layoutNewVerifyIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/new-verify/index'
import { Route as unguardedUnguarded_layoutVerificationResultRouteImport } from './routes/(unguarded)/_unguarded_layout/verification/result'
import { Route as unguardedUnguarded_layoutVerifyResultRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/result'
import { Route as unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/new-verify/$token/index'
import { Route as unguardedUnguarded_layoutVerifyLinkIndexRouteImport } from './routes/(unguarded)/_unguarded_layout/verify/$link/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const unguardedUnguarded_layoutRoute =
  unguardedUnguarded_layoutRouteImport.update({
    id: '/(unguarded)/_unguarded_layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const unguardedUnguarded_layoutNewVerifyIndexRoute =
  unguardedUnguarded_layoutNewVerifyIndexRouteImport.update({
    id: '/new-verify/',
    path: '/new-verify/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerificationResultRoute =
  unguardedUnguarded_layoutVerificationResultRouteImport.update({
    id: '/verification/result',
    path: '/verification/result',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyResultRoute =
  unguardedUnguarded_layoutVerifyResultRouteImport.update({
    id: '/verify/result',
    path: '/verify/result',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutNewVerifyTokenIndexRoute =
  unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport.update({
    id: '/new-verify/$token/',
    path: '/new-verify/$token/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)
const unguardedUnguarded_layoutVerifyLinkIndexRoute =
  unguardedUnguarded_layoutVerifyLinkIndexRouteImport.update({
    id: '/verify/$link/',
    path: '/verify/$link/',
    getParentRoute: () => unguardedUnguarded_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/new-verify/': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/new-verify/$token/': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/new-verify': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/new-verify/$token': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/verify/$link': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/(unguarded)/_unguarded_layout': typeof unguardedUnguarded_layoutRouteWithChildren
  '/(unguarded)/_unguarded_layout/verification/result': typeof unguardedUnguarded_layoutVerificationResultRoute
  '/(unguarded)/_unguarded_layout/verify/result': typeof unguardedUnguarded_layoutVerifyResultRoute
  '/(unguarded)/_unguarded_layout/new-verify/': typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  '/(unguarded)/_unguarded_layout/new-verify/$token/': typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  '/(unguarded)/_unguarded_layout/verify/$link/': typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/verification/result'
    | '/verify/result'
    | '/new-verify/'
    | '/new-verify/$token/'
    | '/verify/$link/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/verification/result'
    | '/verify/result'
    | '/new-verify'
    | '/new-verify/$token'
    | '/verify/$link'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/(unguarded)/_unguarded_layout'
    | '/(unguarded)/_unguarded_layout/verification/result'
    | '/(unguarded)/_unguarded_layout/verify/result'
    | '/(unguarded)/_unguarded_layout/new-verify/'
    | '/(unguarded)/_unguarded_layout/new-verify/$token/'
    | '/(unguarded)/_unguarded_layout/verify/$link/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  unguardedUnguarded_layoutRoute: typeof unguardedUnguarded_layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout': {
      id: '/(unguarded)/_unguarded_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof unguardedUnguarded_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(unguarded)/_unguarded_layout/new-verify/': {
      id: '/(unguarded)/_unguarded_layout/new-verify/'
      path: '/new-verify'
      fullPath: '/new-verify/'
      preLoaderRoute: typeof unguardedUnguarded_layoutNewVerifyIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verification/result': {
      id: '/(unguarded)/_unguarded_layout/verification/result'
      path: '/verification/result'
      fullPath: '/verification/result'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerificationResultRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/result': {
      id: '/(unguarded)/_unguarded_layout/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyResultRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/new-verify/$token/': {
      id: '/(unguarded)/_unguarded_layout/new-verify/$token/'
      path: '/new-verify/$token'
      fullPath: '/new-verify/$token/'
      preLoaderRoute: typeof unguardedUnguarded_layoutNewVerifyTokenIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
    '/(unguarded)/_unguarded_layout/verify/$link/': {
      id: '/(unguarded)/_unguarded_layout/verify/$link/'
      path: '/verify/$link'
      fullPath: '/verify/$link/'
      preLoaderRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRouteImport
      parentRoute: typeof unguardedUnguarded_layoutRoute
    }
  }
}

interface unguardedUnguarded_layoutRouteChildren {
  unguardedUnguarded_layoutVerificationResultRoute: typeof unguardedUnguarded_layoutVerificationResultRoute
  unguardedUnguarded_layoutVerifyResultRoute: typeof unguardedUnguarded_layoutVerifyResultRoute
  unguardedUnguarded_layoutNewVerifyIndexRoute: typeof unguardedUnguarded_layoutNewVerifyIndexRoute
  unguardedUnguarded_layoutNewVerifyTokenIndexRoute: typeof unguardedUnguarded_layoutNewVerifyTokenIndexRoute
  unguardedUnguarded_layoutVerifyLinkIndexRoute: typeof unguardedUnguarded_layoutVerifyLinkIndexRoute
}

const unguardedUnguarded_layoutRouteChildren: unguardedUnguarded_layoutRouteChildren =
  {
    unguardedUnguarded_layoutVerificationResultRoute:
      unguardedUnguarded_layoutVerificationResultRoute,
    unguardedUnguarded_layoutVerifyResultRoute:
      unguardedUnguarded_layoutVerifyResultRoute,
    unguardedUnguarded_layoutNewVerifyIndexRoute:
      unguardedUnguarded_layoutNewVerifyIndexRoute,
    unguardedUnguarded_layoutNewVerifyTokenIndexRoute:
      unguardedUnguarded_layoutNewVerifyTokenIndexRoute,
    unguardedUnguarded_layoutVerifyLinkIndexRoute:
      unguardedUnguarded_layoutVerifyLinkIndexRoute,
  }

const unguardedUnguarded_layoutRouteWithChildren =
  unguardedUnguarded_layoutRoute._addFileChildren(
    unguardedUnguarded_layoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  unguardedUnguarded_layoutRoute: unguardedUnguarded_layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
